# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ER2XML', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='table',
        ),
        migrations.AddField(
            model_name='column',
            name='colId',
            field=models.CharField(default='non', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constraint',
            name='referredCol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constraint',
            name='referredTable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='isEntity',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='tableId',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='column',
            name='maxOccur',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='minOccur',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constr', to='ER2XML.Column'),
        ),
    ]
