# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER2XML', '0004_auto_20170324_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=16)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
